cache:
  apt: true
  directories:
    - dpdk-16.07
    - dpdk-18.05
    - dpdk-19.02
    - tcpdump-4.9.3
    - netmap-11.1

language: c++

compiler:
  - gcc
  - clang

env:
  global:
    - FLAGS="--enable-ip6 --enable-json --disable-linuxmodule"
    - CXXFLAGS="-std=gnu++11"
  matrix:
    - FRAMEWORK=vanilla
    - FRAMEWORK=umultithread
    - FRAMEWORK=netmap VERSION=11.1
    - FRAMEWORK=dpdk VERSION=16.07
    - FRAMEWORK=dpdk VERSION=18.05
    - FRAMEWORK=dpdk VERSION=19.02

script:
  - if [ $FRAMEWORK = "netmap" ]; then
      FRAMEWORK_FLAGS="--enable-user-multithread --with-netmap=`pwd`/netmap-$VERSION/sys/";
    fi

  - if [ $FRAMEWORK = "dpdk" ] ; then
      FRAMEWORK_FLAGS="--enable-user-multithread --enable-dpdk";
      export RTE_SDK=`pwd`/dpdk-$VERSION;
      export RTE_TARGET=x86_64-native-linuxapp-gcc;
      if [ ! -e "$RTE_SDK/$RTE_TARGET/include/rte_version.h" -o ! -e "$RTE_SDK/$RTE_TARGET/build/lib/librte_eal/linuxapp/eal/librte_eal.a" ]; then
            wget http://fast.dpdk.org/rel/dpdk-$VERSION.tar.gz &&
            tar -zxf dpdk-$VERSION.tar.gz &&
            cd dpdk-$VERSION &&
            sed -i "s/CONFIG_RTE_ENABLE_AVX=.*/CONFIG_RTE_ENABLE_AVX=n/g" config/common_base &&
            sed -i "s/CONFIG_RTE_KNI_KMOD=.*/CONFIG_RTE_KNI_KMOD=n/g" config/common_linuxapp &&
            sed -i "s/CONFIG_RTE_LIBRTE_KNI=.*/CONFIG_RTE_LIBRTE_KNI=n/g" config/common_linuxapp &&
            sed -i "s/CONFIG_RTE_EAL_IGB_UIO=.*/CONFIG_RTE_EAL_IGB_UIO=n/g" config/common_linuxapp &&
            sed -i "s/CONFIG_RTE_LIBRTE_VIRTIO_PMD=.*/CONFIG_RTE_LIBRTE_VIRTIO_PMD=n/g" config/common_base ;
            make config T=$RTE_TARGET &&
            make install T=$RTE_TARGET &&
            cd ..;
      fi;
    fi

  - if [ $FRAMEWORK = "umultithread" ] ; then
      FRAMEWORK_FLAGS="--enable-user-multithread";
    fi

  - ./configure $CONFIG $FLAGS $FRAMEWORK_FLAGS && make
  - make check

install:
  - export PATH=$PATH:`pwd`/tcpdump-4.9.3/sbin/ && if [ ! -e "tcpdump-4.9.3/sbin/tcpdump" ] ; then wget http://www.tcpdump.org/release/tcpdump-4.9.3.tar.gz && tar -zxf tcpdump-4.9.3.tar.gz && cd tcpdump-4.9.3 && ./configure --prefix=`pwd` && make && make install && cd .. ; fi
  - if [ $FRAMEWORK = "netmap" -a ! -e "netmap-11.1/sys/net/netmap.h" ] ; then wget https://github.com/luigirizzo/netmap/archive/v11.1.tar.gz && tar -xvf v11.1.tar.gz ; fi

addons:
  apt:
    packages:
        - libpcap-dev
        - time
        - linux-headers-generic
        - libnuma-dev
    config:
        retries: true

sudo: false

dist: bionic
